### ISSUE TITLE
You have to f****** learn f****** git with the command line

### ISSUE THREAD

**Issue by MatiasConTilde** [Javojav/javojav.com#4]
You know what I mean.
WWAaaaaAAaaAAYyYyYYYYYyYyYyyy too many commits.
Use this: https://www.youtube.com/watch?v=oK8EvVeVltE&index=5&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV

**Comment by Javojav** [comment]
@ANyanCatFan 
Man look at my f****** last commit!
@ANyanCatFan 
I did it with f****** Git man.
@ANyanCatFan 
Are you f****** happy now? 
@ANyanCatFan

**Comment by MatiasConTilde** [comment]
YYYYooooOO ooOo chiilll maaanananaaaaaaaaaan
YYYyoooOoOoOOoo maaaaAAAaaaAaaann chiiilll

**Comment by Javojav** [comment]
@ANyanCatFan I am f****** chilled maaaaAAAaaaAaaann I am f****** chilled.
Yo need to f****** chiiilll.
MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN

**Comment by Javojav** [comment]
@ANyanCatFan please answer:
Are you now f****** happy?

**Comment by MatiasConTilde** [comment]
Sí
